<?php

/**
 * @package     J2Commerce
 * @subpackage  com_j2commercemigrator
 *
 * @copyright   (C)2024-2026 J2Commerce, LLC <https://www.j2commerce.com>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

declare(strict_types=1);

namespace J2Commerce\Component\J2commercemigrator\Administrator\Service;

use J2Commerce\Component\J2commercemigrator\Administrator\Helper\MigrationLogger;
use J2Commerce\Component\J2commercemigrator\Administrator\Service\Reader\SourceDatabaseReaderInterface;
use Joomla\CMS\Factory;
use Joomla\Database\DatabaseInterface;

/**
 * Copies a source Joomla site's `images/` directory into the current (target) site when the
 * two sites share a server but live under different docroots. Used only in Source Connection
 * Mode B ("same server, different database") — Mode A does nothing (already local) and
 * Mode C has no filesystem access to the source.
 */
class ImageCopyService
{
    public function __construct(
        private MigrationLogger $logger,
        private ?SourceDatabaseReaderInterface $sourceReader = null
    ) {}

    /**
     * Copy the source site's images tree into this site's `images/` folder.
     *
     * Resolution of the source root:
     *   - If `{path}/images/` exists, treat `{path}/images/` as the source root (Joomla docroot supplied).
     *   - Otherwise treat `{path}/` itself as the source root.
     *
     * The whole tree under the resolved source root is copied into `JPATH_ROOT/images/`,
     * preserving structure. Files already present with the same size+mtime are skipped so
     * re-runs are cheap. The target `images/shop/` folder is pre-created up front so
     * downstream Rebuild Images tooling always has it to work with, even if the source
     * had no j2store subfolder.
     *
     * @return array{ok:bool, copied?:int, skipped?:int, bytes?:int, error?:string, note?:string}
     */
    public function copyFromSource(string $sourceImagesPath): array
    {
        $sourceImagesPath = rtrim(str_replace('\\', '/', trim($sourceImagesPath)), '/');

        if ($sourceImagesPath === '') {
            return ['ok' => false, 'error' => 'Source images path is required.'];
        }

        if (!is_dir($sourceImagesPath)) {
            return ['ok' => false, 'error' => 'Source path does not exist or is not a directory: ' . $sourceImagesPath];
        }

        // When a source DB reader is wired up (mode B/C), run the manifest-driven copy:
        // walk product/variant/category/manufacturer/option image columns, dedupe into a
        // unique list, and copy only those files into target/images/shop/main
        // (thumbs are regenerated by Rebuild Product Images). Far tighter than
        // the blind tree copy and gives orphan/missing-source reporting for free.
        if ($this->sourceReader !== null) {
            return $this->copyViaManifest($sourceImagesPath);
        }

        $sourceRoot = is_dir($sourceImagesPath . '/images') ? $sourceImagesPath . '/images' : $sourceImagesPath;
        $target     = rtrim(str_replace('\\', '/', JPATH_ROOT), '/') . '/images';

        if (!is_dir($target) && !@mkdir($target, 0755, true) && !is_dir($target)) {
            return ['ok' => false, 'error' => 'Target images/ directory could not be created: ' . $target];
        }

        // Pre-create target/images/shop/ so Rebuild Images and downstream tooling
        // always have a predictable destination, even when the source tree didn't
        // organize its product images under shop/.
        $shopTarget = $target . '/shop';
        if (!is_dir($shopTarget)) {
            @mkdir($shopTarget, 0755, true);
        }

        $this->logger->info("ImageCopyService: copying {$sourceRoot} -> {$target}");

        $copied        = 0;
        $skipped       = 0;
        $bytes         = 0;
        $sourceRootLen = strlen($sourceRoot);

        try {
            $iter = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($sourceRoot, \FilesystemIterator::SKIP_DOTS),
                \RecursiveIteratorIterator::SELF_FIRST
            );

            foreach ($iter as $item) {
                $rel  = substr($item->getPathname(), $sourceRootLen + 1);
                $rel  = str_replace('\\', '/', $rel);
                $dest = $target . '/' . $rel;

                if ($item->isDir()) {
                    if (!is_dir($dest) && !@mkdir($dest, 0755, true) && !is_dir($dest)) {
                        $this->logger->warning("ImageCopyService: could not create directory {$dest}");
                    }
                    continue;
                }

                if (is_file($dest) && filesize($dest) === $item->getSize() && filemtime($dest) >= $item->getMTime()) {
                    $skipped++;
                    continue;
                }

                $destDir = \dirname($dest);
                if (!is_dir($destDir)) {
                    @mkdir($destDir, 0755, true);
                }

                if (@copy($item->getPathname(), $dest)) {
                    $copied++;
                    $bytes += (int) $item->getSize();
                } else {
                    $this->logger->warning("ImageCopyService: copy failed for {$item->getPathname()}");
                }
            }
        } catch (\Throwable $e) {
            $this->logger->error('ImageCopyService failed: ' . $e->getMessage());
            return ['ok' => false, 'error' => $e->getMessage()];
        }

        $this->logger->info("ImageCopyService: done. copied={$copied}, skipped={$skipped}, bytes={$bytes}");

        $result = ['ok' => true, 'copied' => $copied, 'skipped' => $skipped, 'bytes' => $bytes];
        if (!is_dir($sourceRoot . '/j2store')) {
            $result['note'] = 'Source had no j2store/ subfolder — the target shop/ folder was pre-created empty so image rebuild tools can populate it.';
        }

        return $result;
    }

    /**
     * Manifest-driven copy (mode B/C): reads image references from the source DB,
     * copies only those files into shop/main/ (thumbs regenerated by Rebuild).
     */
    private function copyViaManifest(string $sourceImagesPath): array
    {
        $manifestSvc = new ImageManifestService($this->sourceReader, $this->logger);
        $manifest    = $manifestSvc->build();

        if (empty($manifest)) {
            $diag = $manifestSvc->getLastDiagnostics();
            $note = 'No product image references were found in the source database — nothing to copy.';

            // Pack the diagnostic into a compact, human-readable string so the store owner
            // can see which tables/columns were inspected and whether any data was seen.
            $parts = [];
            foreach (($diag['tables'] ?? []) as $tbl => $info) {
                if (empty($info['present'])) {
                    $parts[] = "{$tbl}=missing";
                    continue;
                }
                foreach (($info['columns'] ?? []) as $col => $cd) {
                    if (!($cd['exists'] ?? false)) {
                        $parts[] = "{$tbl}.{$col}=col-missing";
                    } else {
                        $parts[] = "{$tbl}.{$col}=rows:{$cd['rows_with_value']}/added:{$cd['paths_added']}";
                    }
                }
            }
            if (!empty($parts)) {
                $note .= ' Scan details — prefix=' . ($diag['source_prefix'] ?? '?') . '; ' . implode(', ', $parts);
            }

            return [
                'ok'          => true,
                'copied'      => 0, 'skipped' => 0, 'bytes' => 0, 'missing' => 0,
                'main'        => 0, 'thumbs' => 0, 'thumbs_skipped' => 0, 'total' => 0,
                'note'        => $note,
                'diagnostics' => $diag,
            ];
        }

        // DB-stored paths are ALWAYS relative to the Joomla docroot (e.g.
        // "media/plg_sampledata_j2store/images/...", "images/j2store/products/..."),
        // so the source root needs to be the docroot. If the user pointed directly at
        // the images/ folder, step up so "media/..." paths still resolve.
        $sourceRoot = rtrim(str_replace('\\', '/', $sourceImagesPath), '/');
        if (basename($sourceRoot) === 'images') {
            $sourceRoot = \dirname($sourceRoot);
        }

        // Safety rail: pointing the source path at THIS site's docroot is the #1 UX
        // failure mode (admins clicking "Use Detected Server Path" without editing it).
        // Bail with a clear error instead of reporting every image as missing.
        $targetDocroot = rtrim(str_replace('\\', '/', JPATH_ROOT), '/');
        if (realpath($sourceRoot) !== false && realpath($sourceRoot) === realpath($targetDocroot)) {
            return [
                'ok'    => false,
                'error' => 'The source path points at THIS site (the migration target). Edit it to point at the SOURCE site\'s Joomla root — e.g. replace the last path segment with the source site\'s folder name.',
            ];
        }

        $stats = $manifestSvc->copyByManifest($manifest, $sourceRoot);

        if (isset($stats['error'])) {
            return ['ok' => false, 'error' => $stats['error']];
        }

        // Rewrite the TARGET j2commerce image-path columns so Rebuild Product Images can
        // find the newly-copied files on disk. Without this, DB paths still reference the
        // source site's filesystem (media/plg_sampledata_j2store/... etc.) and the scan
        // reports 0 ready-for-rebuild even though copy succeeded.
        $targetDb   = Factory::getContainer()->get(DatabaseInterface::class);
        $dbRewrites = $manifestSvc->rewriteTargetImagePaths($manifest, $targetDb);

        $out = [
            'ok'             => true,
            'copied'         => $stats['copied'],
            'skipped'        => $stats['skipped'],
            'bytes'          => $stats['bytes'],
            'missing'        => $stats['missing'],
            'main'           => $stats['main'],
            'thumbs'         => $stats['thumbs'],
            'thumbs_skipped' => $stats['thumbs_skipped'] ?? 0,
            'total'          => count($manifest),
            'db_rewrites'    => $dbRewrites,
        ];

        if ($stats['missing'] > 0) {
            $sample     = implode(', ', array_slice($stats['missing_paths'], 0, 5));
            $more       = $stats['missing'] > 5 ? ' (and ' . ($stats['missing'] - 5) . ' more — see the activity log)' : '';
            $out['note'] = "{$stats['missing']} image(s) referenced by the source DB were not found on the source filesystem: {$sample}{$more}";
            foreach ($stats['missing_paths'] as $p) {
                $this->logger->warning('ImageManifestService: missing source file — ' . $p);
            }
        }

        return $out;
    }
}
